import physics_numba
import physics_numpy

run_until_stopping = physics_numba.run_until_stopping
run_to_next_collision_or_stop = physics_numba.run_to_next_collision_or_stop

run_until_stopping_np = physics_numpy.run_until_stopping
run_to_next_collision_or_stop_np = physics_numpy.run_to_next_collision_or_stop
